// @ts-ignore - generated by `npm run cf:build` before Wrangler bundles this worker.
import openNextWorker from "./.open-next/worker.js";
import { handleCloudflareAsrStream } from "./lib/voice/cloudflareAsrStream";

type CloudflareEnv = Record<string, unknown>;

export default {
  async fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: { waitUntil(promise: Promise<unknown>): void }
  ): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/api/asr/stream") {
      return handleCloudflareAsrStream(request, env, {
        waitUntil: (promise) => ctx.waitUntil(promise),
      });
    }

    return openNextWorker.fetch(request, env, ctx);
  },
};
