import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { annotateAnswers } from "../lib/prompts/annotateAnswers";
import { generateReport } from "../lib/prompts/finalReport";
import type { InterviewHistoryRecord } from "../lib/historyStore";
import type { Session } from "../lib/types";

loadEnvLocal();

const now = Date.now();
const sessionId = "demo-history-session-behavioral-001";

async function main() {
  const session = createBehavioralDemoSession();
  const report = await generateReport(session);
  const annotations = await annotateAnswers(session, report);
  report.roundReviews = annotations.roundReviews;
  report.answerAnnotations = annotations.answerAnnotations;
  report.annotationSummaries = annotations.annotationSummaries;

  const record: InterviewHistoryRecord = {
    id: session.id,
    ownerId: session.ownerId,
    sessionId: session.id,
    resume: session.resume,
    company: session.company,
    jobTitle: session.jobTitle,
    jd: session.jd,
    interviewType: session.interviewType,
    language: session.language,
    persona: session.persona,
    difficulty: session.difficulty,
    mode: session.mode,
    rounds: session.rounds,
    report,
    createdAt: session.createdAt,
    reportedAt: now,
  };

  upsertHistoryRecord(record);
  console.log(
    `Behavioral MBTI demo generated by AI: ${report.mbtiReport?.mbtiType ?? "unknown"} (${record.id})`
  );
}

function createBehavioralDemoSession(): Session {
  return {
    id: sessionId,
    ownerId: process.env.DEMO_OWNER_ID || "demo-user",
    resume:
      "教育背景：某 211 高校市场营销专业，本科。\n\n实习经历：\n1. 快消品牌市场部实习生\n- 参与校园新品推广活动策划与执行\n- 负责社群用户沟通、活动报名整理、现场反馈收集\n- 协助复盘活动流程并整理用户反馈\n\n2. 学生会外联负责人\n- 负责赞助沟通、活动协调和跨部门推进\n- 带领 5 人小组完成校级活动物料、场地和嘉宾对接\n\n技能：\n- 用户沟通、活动执行、基础数据整理、PPT 汇报",
    company: "Demo 消费品公司",
    jobTitle: "市场管培生",
    jd:
      "岗位职责：参与品牌活动策划、用户洞察、渠道沟通和项目推进；需要在多方协作中完成执行落地。\n岗位要求：具备较强沟通表达、执行力、协作意识、复盘意识和一定抗压能力。",
    interviewType: "behavioral",
    language: "zh",
    persona: "warm_hr",
    difficulty: "medium",
    mode: "practice",
    provider: process.env.DEMO_LLM_PROVIDER || process.env.LLM_PROVIDER || "deepseek",
    model: process.env.DEMO_LLM_MODEL || process.env.DEEPSEEK_MODEL || "deepseek-chat",
    thinkingEnabled: false,
    plan: {
      focusAreas: ["团队协作", "冲突处理", "压力反应", "复盘意识", "岗位匹配"],
      plannedQuestions: [
        "请讲一个你在团队里推动别人配合完成任务的经历。",
        "如果团队成员临时掉链子，你当时是怎么处理的？",
        "你觉得自己在高压和不确定情况下通常会怎么做？",
      ],
      openingQuestion: "请讲一个你在团队里推动别人配合完成任务的经历。",
    },
    rounds: [
      {
        question: "请讲一个你在团队里推动别人配合完成任务的经历。",
        answer:
          "我想讲学生会外联活动的经历。当时我们要办一场校级分享会，赞助方、场地老师、宣传组和嘉宾时间都要对齐，但一开始大家的信息非常分散，很多事情都靠口头同步。我当时先把任务拆成赞助物料、场地审批、宣传排期和嘉宾确认四条线，然后建了一个共享表格，每天晚上十点前更新进度。因为宣传组一开始觉得时间还早，没有及时出海报，我就主动去跟他们沟通，把赞助方的露出要求和报名截止时间讲清楚，也帮他们整理了文案要点。最后活动按时落地，现场大概有一百五十多人参加。这个经历让我意识到，团队协作里不能只等别人配合，很多时候要先把信息和责任边界整理清楚。",
        isFollowUp: false,
      },
      {
        question: "如果团队成员临时掉链子，你当时是怎么处理的？",
        answer:
          "有一次负责物料的同学临时说自己考试周忙不过来，原本第二天要确认易拉宝和手卡。我当时其实有点着急，但没有直接责怪他，因为我觉得先把事情救回来更重要。我先问他已经做到哪一步，发现设计稿有了但还没联系打印店，于是我把剩下的事情拆成两块：我自己去确认打印店和价格，让另一个同学帮忙核对文案。后来物料按时做好了。事后我也和那个同学单独聊了一下，确认后续类似任务如果有风险要提前说。可能我当时处理得还不够强硬，但我更倾向于先保证结果，再回头复盘合作方式。",
        isFollowUp: true,
      },
      {
        question: "你觉得自己在高压和不确定情况下通常会怎么做？",
        answer:
          "我一般会先把最影响结果的事情列出来，而不是马上陷入情绪里。比如活动报名人数低于预期的时候，我会先看是不是宣传渠道没触达，还是报名门槛太高，然后再决定是加推社群、请老师转发，还是调整文案。压力大的时候我会比较想快速找到抓手，所以有时候会自己先把方案推起来，再去拉别人一起补充。这个优点是推进比较快，风险是可能一开始听取别人意见不够充分。所以我现在会提醒自己，先给一个初版方案，但一定留时间让团队补充。",
        isFollowUp: false,
      },
    ],
    currentQuestion: null,
    currentIsFollowUp: false,
    status: "finished",
    report: null,
    createdAt: now - 1000 * 60 * 60,
  };
}

function upsertHistoryRecord(record: InterviewHistoryRecord) {
  const dbPath = join(process.cwd(), "data", "interview-history.json");
  const current = readHistoryDB(dbPath);
  const nextRecords = [
    record,
    ...current.records.filter((item) => item.id !== record.id && item.sessionId !== record.sessionId),
  ];
  writeFileSync(dbPath, JSON.stringify({ records: nextRecords }, null, 2) + "\n", "utf-8");
}

function readHistoryDB(dbPath: string): { records: InterviewHistoryRecord[] } {
  try {
    const raw = readFileSync(dbPath, "utf-8");
    const parsed = JSON.parse(raw) as { records?: InterviewHistoryRecord[] };
    return { records: Array.isArray(parsed.records) ? parsed.records : [] };
  } catch {
    return { records: [] };
  }
}

function loadEnvLocal() {
  const envPath = join(process.cwd(), ".env.local");
  if (!existsSync(envPath)) return;
  const raw = readFileSync(envPath, "utf-8");
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index <= 0) continue;
    const key = trimmed.slice(0, index).trim();
    const value = trimmed.slice(index + 1).trim().replace(/^['"]|['"]$/g, "");
    if (!process.env[key]) process.env[key] = value;
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
